subplot(2,1,1)
plot(Timestamp,Sl3Voltage)
title('test gent bij T= 25°C, slave3 en ontlaadperiodes 15A')
xlabel('tijd(s)')
ylabel('spanning(V)')
subplot(2,1,2)
plot(Timestamp,Current)
xlabel('tijd(s)')
ylabel('stroom(A)')
