subplot(2,1,1)
title('HPPC test bij T= 25°C en cel 1')
xlabel('tijd(s)')
plot(timeSeconds,Voltage)
title('HPPC test bij T= 25°C en cel 1')
xlabel('tijd(s)')
ylabel('spanning(V)')
subplot(2,1,2)
plot(timeSeconds,Current)
xlabel('tijd(s)')
ylabel('stroom(A)')
